In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [6]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [7]:
np.ones(4)

array([1., 1., 1., 1.])

In [8]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [11]:
np.arange(5,10,2)

array([5, 7, 9])

In [12]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [7]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [17]:
np.eye(3,4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.eye(3,4,k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [22]:
np.random.rand(1,4)

array([[0.85257293, 0.83434199, 0.17103167, 0.63045064]])

In [23]:
np.random.randn(2,3)

array([[ 1.30171563, -1.94677347,  0.19248457],
       [ 0.35062874, -0.80141225,  0.39480754]])

In [27]:
np.random.randint(1,50,4)

array([ 8, 29, 23, 36])

In [29]:
x=np.random.randint(1,40,size=(4,5))

In [30]:
x

array([[39, 19, 35,  4, 36],
       [ 8, 11, 38, 19,  9],
       [ 6, 34,  4, 30, 28],
       [11, 22, 14, 32, 25]])

In [34]:
x.reshape((10,2))

array([[39, 19],
       [35,  4],
       [36,  8],
       [11, 38],
       [19,  9],
       [ 6, 34],
       [ 4, 30],
       [28, 11],
       [22, 14],
       [32, 25]])

In [41]:
x.max(axis=1)  #he result of x.max(axis=1) is a 1D array 

array([39, 38, 34, 32])

In [39]:
x.argmax(axis=1)

array([0, 2, 1, 3], dtype=int32)

In [37]:
x.min()

4

In [38]:
x.argmin()

3

In [42]:
x.shape

(4, 5)

In [43]:
x.dtype

dtype('int32')